### ISSUE TITLE
"No such input `name`" in notebook 9

### ISSUE THREAD

**Issue by aidalgol** [ash-project/ash_tutorial#11]
After correctly filling out the exercise codeblock, I get this error on the "Create a Representative:" codeblock.
```console
** (Ash.Error.Invalid) Invalid Error

* No such input `name` for action Tutorial.Support.Representative.create

No valid inputs exist

  (elixir 1.16.2) lib/process.ex:860: Process.info/2
  (ash 3.0.0-rc.13) lib/ash/error/invalid/no_such_input.ex:5: Ash.Error.Invalid.NoSuchInput.exception/1
  (ash 3.0.0-rc.13) lib/ash/changeset/changeset.ex:1813: anonymous fn/4 in Ash.Changeset.cast_params/4
  (stdlib 4.3.1.3) maps.erl:411: :maps.fold_1/3
  (ash 3.0.0-rc.13) lib/ash/changeset/changeset.ex:1532: Ash.Changeset.handle_params/4
  (ash 3.0.0-rc.13) lib/ash/changeset/changeset.ex:1448: Ash.Changeset.do_for_action/4
  (elixir 1.16.2) elixir.erl:405: :elixir.eval_external_handler/3
  (stdlib 4.3.1.3) erl_eval.erl:748: :erl_eval.do_apply/7
    (elixir 1.16.2) lib/process.ex:860: Process.info/2
    (ash 3.0.0-rc.13) lib/ash/error/invalid.ex:5: Ash.Error.Invalid.exception/1
    (ash 3.0.0-rc.13) /home/aidan/.cache/mix/installs/elixir-1.16.2-erts-13.2.2.7/4c9e15cb5cc9c3b57ec9822200e2567e/deps/splode/lib/splode.ex:211: Ash.Error.to_class/2
    (ash 3.0.0-rc.13) lib/ash/error/error.ex:33: Ash.Error.to_error_class/2
    (ash 3.0.0-rc.13) lib/ash/actions/create/create.ex:131: Ash.Actions.Create.do_run/4
    (ash 3.0.0-rc.13) lib/ash/actions/create/create.ex:46: Ash.Actions.Create.run/4
    (ash 3.0.0-rc.13) lib/ash.ex:1914: Ash.create!/2
    #cell:32t27u3kawca5wdr:4: (file)
```

**Comment by zachdaniel** [comment]
I believe this is fixed now.
