### ISSUE TITLE
The relationship's tutorial throws an exception.

### ISSUE THREAD

**Issue by trickster** [ash-project/ash_tutorial#29]
# ASH Relationships

```elixir
Application.put_env(:ash, :validate_domain_resource_inclusion?, false)
Application.put_env(:ash, :validate_domain_config_inclusion?, false)
Mix.install([{:ash, "~> 3.1.3"}], consolidate_protocols: false)
```

## Section

```elixir
defmodule Tutorial.Support do
  use Ash.Domain

  resources do
    resource Tutorial.Support.Ticket
    resource Tutorial.Support.Representative
  end
end
```

```elixir
defmodule Tutorial.Support.Ticket do
  use Ash.Resource,
    domain: Tutorial.Support,
    data_layer: Ash.DataLayer.Ets

  actions do
    defaults [:read]

    create :create do
      accept [:subject, :description, :status]
    end
  end

  attributes do
    uuid_primary_key :id
    attribute :subject, :string, allow_nil?: false
    attribute :description, :string

    attribute :status, :atom do
      constraints one_of: [:open, :closed]
      default :open
      allow_nil? false
    end

    create_timestamp :created_at
    update_timestamp :updated_at
  end

  relationships do
    belongs_to :representative, Tutorial.Support.Representative
  end
end

defmodule Tutorial.Support.Representative do
  use Ash.Resource,
    domain: Tutorial.Support,
    data_layer: Ash.DataLayer.Ets

  actions do
    defaults [:read]

    create :create do
      accept [:name]
    end
  end

  attributes do
    uuid_primary_key(:id)
    attribute(:name, :string)
  end
end
```

Error

```
Evaluation process terminated - an exception was raised:
    ** (ArgumentError) `Tutorial.Support.Ticket` is not a Spark DSL module.

        Tutorial.Support.Ticket.persisted(:embedded?)
        (spark 2.2.7) lib/spark/dsl/extension.ex:136: Spark.Dsl.Extension.persisted!/3
        (elixir 1.17.1) lib/enum.ex:4301: Enum.filter_list/2
        (ash 3.1.3) lib/ash/domain/verifiers/ensure_no_embeds.ex:13: Ash.Domain.Verifiers.EnsureNoEmbeds.verify/1
        ASH_Relationships.livemd#cell:r6wrurkdgbbkonsp:1: anonymous fn/1 in Tutorial.Support.__verify_spark_dsl__/1
        (elixir 1.17.1) lib/enum.ex:987: Enum."-each/2-lists^foreach/1-0-"/2
        ASH_Relationships.livemd#cell:r6wrurkdgbbkonsp:1: Tutorial.Support.__verify_spark_dsl__/1
        (elixir 1.17.1) lib/enum.ex:987: Enum."-each/2-lists^foreach/1-0-"/2
```

**Comment by zachdaniel** [comment]
🤔 is it possible you are looking at an old version of the tutorial? The domain must be defined either in a different file or after the resources if they are defined in the same file. From what I can tell, that is the order they appear in the tutorial.
