### ISSUE TITLE
Invalid error when following "Ash: 8 - Relationships"

### ISSUE THREAD

**Issue by Welteam** [ash-project/ash_tutorial#31]
### How to reproduce

1. Select the tutorial about relationships
2. Copy/paste the given solution in the first code cell where shown by the comment
3. Execute all code cells up to the last one where a ticket is created

### What is the error?

When executing the last cell in order to create a ticket owned by a representative, the following error is thrown:

```
** (Ash.Error.Invalid) 
Invalid Error

* No such input `representative_id` for action Tutorial.Support.Ticket.create

The attribute exists on Tutorial.Support.Ticket, but is not accepted by Tutorial.Support.Ticket.create

The attribute is currently `public?: false`, which means that it is not accepted when using `:*`, i.e in `accept :*`.

Perhaps you meant to make the attribute public, or add it to the accept list for Tutorial.Support.Ticket.create?


Valid Inputs:

* status
* description
* subject


  (ash 3.4.37) lib/ash/error/invalid/no_such_input.ex:5: Ash.Error.Invalid.NoSuchInput."exception (overridable 2)"/1
  (ash 3.4.37) lib/ash/changeset/changeset.ex:2327: anonymous fn/4 in Ash.Changeset.cast_params/4
  (stdlib 6.0) maps.erl:860: :maps.fold_1/4
  (ash 3.4.37) lib/ash/changeset/changeset.ex:2026: Ash.Changeset.handle_params/4
  (ash 3.4.37) lib/ash/changeset/changeset.ex:1906: Ash.Changeset.do_for_action/4
  (elixir 1.17.2) src/elixir.erl:386: :elixir.eval_external_handler/3
  (stdlib 6.0) erl_eval.erl:904: :erl_eval.do_apply/7
    (ash 3.4.37) lib/ash/error/invalid.ex:3: Ash.Error.Invalid.exception/1
    (ash 3.4.37) [redacted]: Ash.Error.to_class/2
    (ash 3.4.37) lib/ash/error/error.ex:66: Ash.Error.to_error_class/2
    (ash 3.4.37) lib/ash/actions/create/create.ex:142: Ash.Actions.Create.do_run/4
    (ash 3.4.37) lib/ash/actions/create/create.ex:50: Ash.Actions.Create.run/4
    (ash 3.4.37) lib/ash.ex:2157: Ash.create!/3
    #cell:nww2r6beij5drstm:4: (file)
```

Indeed, the "representative_id" is not part of the accept list for the ":create" action and the tutorial does not mention adding it.

**Comment by Welteam** [comment]
Sorry I missed the very last line as I was thrown off by the error >.<
